SELECT ts_headline('english', '  Day after day, day after day,  We stuck, nor breath nor motion,  As idle as a painted Ship  Upon a painted Ocean.  Water, water, every where  And all the boards did shrink;  Water, water, every where,  Nor any drop to drink.  S. T. Coleridge (1772-1834)  ', to_tsquery('english', 'Coleridge & stuck'), 'MaxFragments=2,FragmentDelimiter=***');
                                                                                                                     ts_headline                                                                                                                     
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 after day, day after day,  We <b>stuck</b>, nor breath nor motion,  As idle as a painted Ship  Upon a painted Ocean.  Water, water, every where  And all the boards did shrink;  Water, water, every where***drop to drink.  S. T. <b>Coleridge</b>
(1 row)

