SELECT ts_headline('english', '  Day after day, day after day,  We stuck, nor breath nor motion,  As idle as a painted Ship  Upon a painted Ocean.  Water, water, every where  And all the boards did shrink;  Water, water, every where,  Nor any drop to drink.  S. T. Coleridge (1772-1834)  ', to_tsquery('english', 'breath&motion&water'));
                                                  ts_headline                                                   
----------------------------------------------------------------------------------------------------------------
 <b>breath</b> nor <b>motion</b>,  As idle as a painted Ship  Upon a painted Ocean.  <b>Water</b>, <b>water</b>
(1 row)

