SELECT ts_headline('english', '  <html>  <!-- some comment -->  <body>  Sea view wow <u>foo bar</u> <i>qq</i>  <a href="http://www.google.com/foo.bar.html" target="_blank">YES &nbsp;</a>  ff-bg  <script>  document.write(15);  </script>  </body>  </html>',  to_tsquery('english', 'sea&foo'), 'HighlightAll=true');
                                                                                                                 ts_headline                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   <html>  <!-- some comment -->  <body>  <b>Sea</b> view wow <u><b>foo</b> bar</u> <i>qq</i>  <a href="http://www.google.com/foo.bar.html" target="_blank">YES &nbsp;</a>  ff-bg  <script>  document.write(15);  </script>  </body>  </html>
(1 row)

