SELECT ts_headline('english', '  Day after day, day after day,  We stuck, nor breath nor motion,  As idle as a painted Ship  Upon a painted Ocean.  Water, water, every where  And all the boards did shrink;  Water, water, every where,  Nor any drop to drink.  S. T. Coleridge (1772-1834)  ', to_tsquery('english', 'ocean'), 'MaxFragments=1');
                                                                                                ts_headline                                                                                                 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 after day,  We stuck, nor breath nor motion,  As idle as a painted Ship  Upon a painted <b>Ocean</b>.  Water, water, every where  And all the boards did shrink;  Water, water, every where,  Nor any drop
(1 row)

