SELECT '' AS to_char_7, to_char(d1, 'HH24--text--MI--text--SS')  FROM TIMESTAMP_TBL;
 to_char_7 |        to_char         
-----------+------------------------
           | 
           | 
           | 00--text--00--text--00
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--02
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 00--text--00--text--00
           | 03--text--04--text--05
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 18--text--19--text--20
           | 08--text--14--text--01
           | 13--text--14--text--02
           | 12--text--14--text--03
           | 03--text--14--text--04
           | 02--text--14--text--05
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--00
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 18--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
           | 17--text--32--text--01
(63 rows)

