SELECT '' AS fifteen, r1.*, r2.*  FROM RELTIME_TBL r1, RELTIME_TBL r2  WHERE r1.f1 > r2.f1  ORDER BY r1.f1, r2.f1;
 fifteen |    f1    |    f1     
---------+----------+-----------
         | 00:01:00 | -00:00:14
         | 05:00:00 | -00:00:14
         | 05:00:00 | 00:01:00
         | 10 days  | -00:00:14
         | 10 days  | 00:01:00
         | 10 days  | 05:00:00
         | 3 mons   | -00:00:14
         | 3 mons   | 00:01:00
         | 3 mons   | 05:00:00
         | 3 mons   | 10 days
         | 34 years | -00:00:14
         | 34 years | 00:01:00
         | 34 years | 05:00:00
         | 34 years | 10 days
         | 34 years | 3 mons
(15 rows)

