SELECT * FROM chkumapping();
     umname     |    umserver    |         umoptions         
----------------+----------------+---------------------------
 highgo         | sv1            | {user=CURRENT_USER}
 current_user   | sv2            | {"user=\"current_user\""}
 highgo         | sv3            | {user=USER}
 user           | sv4            | {"user=\"USER\""}
 highgo         | sv5            | {user=SESSION_USER}
                | sv6            | {user=PUBLIC}
 Public         | sv7            | {"user=\"Public\""}
 testrolx       | sv8            | {user=testrolx}
 regression_bob | useless_server | 
(9 rows)

