select aggfns(distinct a,a,c order by c using ~<~,a)  from (values (1,3,'foo'),(0,null,null),(2,2,'bar'),(3,1,'baz')) v(a,b,c),  generate_series(1,2) i;
ERROR:  42883: function aggfns(integer, integer, text) does not exist
LINE 1: select aggfns(distinct a,a,c order by c using ~<~,a)  from (...
               ^
HINT:  No aggregate function matches the given name and argument types. Perhaps you misplaced ORDER BY; ORDER BY must appear after all regular arguments of the aggregate.
