create or replace view agg_view1 as  select aggfns(a,b,c order by c using ~<~)  from (values (1,3,'foo'),(0,null,null),(2,2,'bar'),(3,1,'baz')) v(a,b,c);
ERROR:  42883: function aggfns(integer, integer, text) does not exist
LINE 1: create or replace view agg_view1 as  select aggfns(a,b,c ord...
                                                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
