select aggfns(distinct a,b,c order by a,b,i,c)  from (values (1,1,'foo')) v(a,b,c), generate_series(1,2) i;
ERROR:  42883: function aggfns(integer, integer, text) does not exist
LINE 1: select aggfns(distinct a,b,c order by a,b,i,c)  from (values...
               ^
HINT:  No aggregate function matches the given name and argument types. Perhaps you misplaced ORDER BY; ORDER BY must appear after all regular arguments of the aggregate.
