SELECT um.srvname AS "Server",  um.usename AS "User name",  CASE WHEN umoptions IS NULL THEN '' ELSE '(' || pg_catalog.array_to_string(ARRAY(SELECT pg_catalog.quote_ident(option_name) || ' ' || pg_catalog.quote_literal(option_value) FROM pg_catalog.pg_options_to_table(umoptions)), ', ') || ')' END AS "FDW Options"  FROM pg_catalog.pg_user_mappings um  ORDER BY 1, 2;
     Server     |   User name    |                FDW Options                 
----------------+----------------+--------------------------------------------
 s4             | highgo         | 
 s4             | public         | ("this mapping" 'is public', modified '1')
 s5             | highgo         | (modified '1')
 s6             | highgo         | (username 'test')
 s7             | highgo         | 
 s8             | highgo         | (password 'public')
 s8             | public         | 
 t1             | highgo         | (username 'bob', password 'boo')
 t1             | public         | (modified '1')
 useless_server | regression_bob | 
(10 rows)

