DROP ROLE IF EXISTS foreign_data_user, regress_test_role, regress_test_role2, regress_test_role_super, regress_test_indirect, unpriviled_role;
NOTICE:  00000: role "foreign_data_user" does not exist, skipping
NOTICE:  00000: role "regress_test_role" does not exist, skipping
NOTICE:  00000: role "regress_test_role2" does not exist, skipping
NOTICE:  00000: role "regress_test_role_super" does not exist, skipping
NOTICE:  00000: role "regress_test_indirect" does not exist, skipping
NOTICE:  00000: role "unpriviled_role" does not exist, skipping
DROP ROLE
