explain (costs off)  select event_id  from (select event_id from events  union all  select event_id from other_events) ss  order by event_id;
                          QUERY PLAN                           
---------------------------------------------------------------
 Merge Append
   Sort Key: events.event_id
   ->  Index Only Scan using events_pkey on events
   ->  Sort
         Sort Key: events_child.event_id
         ->  Seq Scan on events_child
   ->  Index Only Scan using other_events_pkey on other_events
(7 rows)

