explain (costs off)  select pct, count(unique1) from  (values (0),(100)) v(pct),  lateral (select * from tenk1 tablesample bernoulli (pct)) ss  group by pct;
                       QUERY PLAN                       
--------------------------------------------------------
 HashAggregate
   Group Key: "*VALUES*".column1
   ->  Nested Loop
         ->  Values Scan on "*VALUES*"
         ->  Sample Scan on tenk1
               Sampling: bernoulli ("*VALUES*".column1)
(6 rows)

