SELECT relname, n_tup_ins, n_tup_upd, n_tup_del, n_live_tup, n_dead_tup  FROM pg_stat_user_tables  WHERE relname like 'trunc_stats_test%' order by relname;
      relname      | n_tup_ins | n_tup_upd | n_tup_del | n_live_tup | n_dead_tup 
-------------------+-----------+-----------+-----------+------------+------------
 trunc_stats_test  |         3 |         0 |         0 |          0 |          0
 trunc_stats_test1 |         4 |         4 |         1 |          1 |          0
 trunc_stats_test2 |         4 |         0 |         0 |          1 |          0
 trunc_stats_test3 |         5 |         0 |         0 |          1 |          0
 trunc_stats_test4 |         3 |         0 |         0 |          1 |          0
(5 rows)

