SELECT table_to_xml('testxmlschema.test1', false, true, '');
                         table_to_xml                          
---------------------------------------------------------------
 <test1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">+
   <a>1</a>                                                   +
   <b>one</b>                                                 +
 </test1>                                                     +
                                                              +
 <test1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">+
   <a>2</a>                                                   +
   <b>two</b>                                                 +
 </test1>                                                     +
                                                              +
 <test1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">+
   <a>-1</a>                                                  +
 </test1>                                                     +
                                                              +
 
(1 row)

