SELECT table_to_xml('testxmlschema.test2', false, false, '');
                         table_to_xml                          
---------------------------------------------------------------
 <test2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">+
                                                              +
 <row>                                                        +
   <z>55</z>                                                  +
   <y>abc</y>                                                 +
   <x>def   </x>                                              +
   <w>98.60</w>                                               +
   <v>2</v>                                                   +
   <u>999</u>                                                 +
   <t>0</t>                                                   +
   <s>21:07:00</s>                                            +
   <r>2009-06-08T21:07:30</r>                                 +
   <q>2009-06-08</q>                                          +
   <o>ABC</o>                                                 +
   <n>true</n>                                                +
   <m>WFla</m>                                                +
 </row>                                                       +
                                                              +
 </test2>                                                     +
 
(1 row)

