select interval 'P0002' AS "year only",  interval 'P0002-10' AS "year month",  interval 'P0002-10-15' AS "year month day",  interval 'P0002T1S' AS "year only plus time",  interval 'P0002-10T1S' AS "year month plus time",  interval 'P0002-10-15T1S' AS "year month day plus time",  interval 'PT10' AS "hour only",  interval 'PT10:30' AS "hour minute";
 year only |   year month    |     year month day      | year only plus time |   year month plus time   |     year month day plus time     | hour only | hour minute 
-----------+-----------------+-------------------------+---------------------+--------------------------+----------------------------------+-----------+-------------
 2 years   | 2 years 10 mons | 2 years 10 mons 15 days | 2 years 00:00:01    | 2 years 10 mons 00:00:01 | 2 years 10 mons 15 days 00:00:01 | 10:00:00  | 10:30:00
(1 row)

