WITH RECURSIVE foo(i) AS  (SELECT i::numeric(3,0) FROM (VALUES(1),(2)) t(i)  UNION ALL  SELECT (i+1)::numeric(10,0) FROM foo WHERE i < 10)  SELECT * FROM foo;
ERROR:  42804: recursive query "foo" column 1 has type numeric(3,0) in non-recursive term but type numeric overall
LINE 1: WITH RECURSIVE foo(i) AS  (SELECT i::numeric(3,0) FROM (VALU...
                                          ^
HINT:  Cast the output of the non-recursive term to the correct type.
