select * from onek,  (values ((select i from  (values(10000), (2), (389), (1000), (2000), ((select 10029))) as foo(i)  order by i asc limit 1))) bar (i)  where onek.unique1 = bar.i;
 unique1 | unique2 | two | four | ten | twenty | hundred | thousand | twothousand | fivethous | tenthous | odd | even | stringu1 | stringu2 | string4 | i 
---------+---------+-----+------+-----+--------+---------+----------+-------------+-----------+----------+-----+------+----------+----------+---------+---
(0 rows)

