CREATE VIEW REVENUE7 (SUPPLIER_NO, TOTAL_REVENUE) AS SELECT L_SUPPKEY, SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT)) FROM LINEITEM  WHERE L_SHIPDATE >= DATE '1996-01-01' AND L_SHIPDATE < DATE '1996-01-01' + INTERVAL '3' MONTH  GROUP BY L_SUPPKEY;
SELECT * FROM (SELECT S_SUPPKEY, S_NAME, S_ADDRESS, S_PHONE, TOTAL_REVENUE FROM SUPPLIER, REVENUE7  WHERE S_SUPPKEY = SUPPLIER_NO AND TOTAL_REVENUE = (SELECT MAX(TOTAL_REVENUE) FROM REVENUE7 ) ORDER BY S_SUPPKEY); 
DROP VIEW REVENUE7;
