SELECT table_name, is_updatable, is_insertable_into,  is_trigger_updatable, is_trigger_deletable,  is_trigger_insertable_into  FROM information_schema.views  WHERE table_name LIKE 'rw_view%'  ORDER BY table_name;
 table_name | is_updatable | is_insertable_into | is_trigger_updatable | is_trigger_deletable | is_trigger_insertable_into 
------------+--------------+--------------------+----------------------+----------------------+----------------------------
 rw_view1   | NO           | NO                 | NO                   | NO                   | YES
 rw_view2   | NO           | NO                 | NO                   | NO                   | NO
(2 rows)

