SELECT table_name, column_name, is_updatable  FROM information_schema.columns  WHERE table_name LIKE E'r_\\_view%'  ORDER BY table_name, ordinal_position;
 table_name | column_name | is_updatable 
------------+-------------+--------------
 rw_view1   | ctid        | NO
 rw_view1   | s           | NO
 rw_view1   | a           | YES
 rw_view1   | c           | NO
 rw_view2   | s           | NO
 rw_view2   | c           | NO
 rw_view2   | t           | NO
 rw_view2   | base_a      | YES
 rw_view2   | ctid        | NO
 rw_view3   | s           | NO
 rw_view3   | c           | NO
 rw_view3   | t           | NO
 rw_view3   | ctid        | NO
(13 rows)

