SELECT * FROM information_schema.views WHERE table_name LIKE E'rw\\_view_' ORDER BY table_name;
 table_catalog | table_schema | table_name |      view_definition      | check_option | is_updatable | is_insertable_into | is_trigger_updatable | is_trigger_deletable | is_trigger_insertable_into 
---------------+--------------+------------+---------------------------+--------------+--------------+--------------------+----------------------+----------------------+----------------------------
 highgo        | public       | rw_view1   |  SELECT base_tbl.a       +| CASCADED     | YES          | YES                | NO                   | NO                   | NO
               |              |            |    FROM base_tbl;         |              |              |                    |                      |                      | 
 highgo        | public       | rw_view2   |  SELECT rw_view1.a       +| NONE         | YES          | YES                | NO                   | NO                   | NO
               |              |            |    FROM rw_view1         +|              |              |                    |                      |                      | 
               |              |            |   WHERE (rw_view1.a > 0); |              |              |                    |                      |                      | 
 highgo        | public       | rw_view3   |  SELECT rw_view2.a       +| CASCADED     | YES          | YES                | NO                   | NO                   | NO
               |              |            |    FROM rw_view2;         |              |              |                    |                      |                      | 
(3 rows)

