EXPLAIN (costs off) UPDATE rw_view2 SET person=person WHERE snoop(person);
                           QUERY PLAN                            
-----------------------------------------------------------------
 Update on base_tbl base_tbl_1
   ->  Subquery Scan on base_tbl
         Filter: snoop(base_tbl.person)
         ->  Subquery Scan on base_tbl_2
               Filter: snoop(base_tbl_2.person)
               ->  LockRows
                     ->  Seq Scan on base_tbl base_tbl_3
                           Filter: (visibility = 'public'::text)
(8 rows)

