SELECT p1.oid, p1.proname  FROM pg_proc as p1  WHERE p1.prorettype IN  ('anyelement'::regtype, 'anyarray'::regtype, 'anynonarray'::regtype,  'anyenum'::regtype, 'anyrange'::regtype)  AND NOT  ('anyelement'::regtype = ANY (p1.proargtypes) OR  'anyarray'::regtype = ANY (p1.proargtypes) OR  'anynonarray'::regtype = ANY (p1.proargtypes) OR  'anyenum'::regtype = ANY (p1.proargtypes) OR  'anyrange'::regtype = ANY (p1.proargtypes))  ORDER BY 2;
 oid  |    proname     
------+----------------
 2296 | anyarray_in
 2502 | anyarray_recv
 2312 | anyelement_in
 3504 | anyenum_in
 2777 | anynonarray_in
 3832 | anyrange_in
  750 | array_in
 2400 | array_recv
 3506 | enum_in
 3532 | enum_recv
 3834 | range_in
 3836 | range_recv
(12 rows)

