SELECT '' AS four, f1 AS abstime, date(f1) AS date  FROM ABSTIME_TBL  WHERE isfinite(f1) AND f1 <> abstime 'now'  ORDER BY date, abstime;
 four |        abstime         |    date    
------+------------------------+------------
      | 1947-05-10 23:59:12+08 | 1947-05-10
      | 1970-01-01 08:00:00+08 | 1970-01-01
      | 1973-01-14 03:14:21+08 | 1973-01-14
      | 1995-05-01 00:30:30+08 | 1995-05-01
(4 rows)

