EXPLAIN (COSTS OFF) SELECT * FROM my_credit_card_normal WHERE f_leak(cnum);
                       QUERY PLAN                        
---------------------------------------------------------
 Hash Join
   Hash Cond: (r.cid = l.cid)
   ->  Seq Scan on credit_card r
         Filter: f_leak(cnum)
   ->  Hash
         ->  Seq Scan on customer l
               Filter: (name = ("current_user"())::text)
(7 rows)

