UPDATE toasttest SET cnt = cnt +1 RETURNING substring(toasttest::text, 1, 200);
ERROR:  42883: function make_tuple_indirect(toasttest) does not exist
LINE 1: SELECT make_tuple_indirect(NEW)
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT make_tuple_indirect(NEW)
CONTEXT:  PL/pgSQL function update_using_indirect() line 1 at assignment
