EXPLAIN (COSTS OFF)  SELECT * FROM  (SELECT depname,  sum(salary) OVER (PARTITION BY depname) depsalary,  min(salary) OVER (PARTITION BY depname || 'A', depname) depminsalary  FROM empsalary) emp  WHERE depname = 'sales';
ERROR:  42P01: relation "empsalary" does not exist
LINE 1: ...ON BY depname || 'A', depname) depminsalary  FROM empsalary)...
                                                             ^
