CREATE FUNCTION foo_sql(int,int) RETURNS setof foo_rescan_t AS 'SELECT i, nextval(''foo_rescan_seq1'') FROM generate_series($1,$2) i;' LANGUAGE SQL;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
ERROR:  42P01: relation "foo_rescan_seq1" does not exist
LINE 1: ... RETURNS setof foo_rescan_t AS 'SELECT i, nextval(''foo_resc...
                                                             ^
