SELECT * FROM (VALUES (1),(2),(3)) v(r) LEFT JOIN ROWS FROM( foo_sql(11,13), foo_mat(11,13) ) WITH ORDINALITY AS f(i1,s1,i2,s2,o) ON (r+i1+i2)<100;
ERROR:  42883: function foo_sql(integer, integer) does not exist
LINE 1: ...OM (VALUES (1),(2),(3)) v(r) LEFT JOIN ROWS FROM( foo_sql(11...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
