SELECT * FROM (VALUES (11,12),(13,15),(16,20)) v(r1,r2), foo_sql(r1,r2) WITH ORDINALITY AS f(i,s,o);
ERROR:  42883: function foo_sql(integer, integer) does not exist
LINE 1: ...* FROM (VALUES (11,12),(13,15),(16,20)) v(r1,r2), foo_sql(r1...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
