create temp view usersview as  SELECT * FROM ROWS FROM(get_users(), generate_series(10,11)) WITH ORDINALITY;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE VIEW
ERROR:  42883: function get_users() does not exist
LINE 1: ...e temp view usersview as  SELECT * FROM ROWS FROM(get_users(...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
