SELECT '' AS Five, NULLIF(a.i,b.i) AS "NULLIF(a.i,b.i)",  NULLIF(b.i, 4) AS "NULLIF(b.i,4)"  FROM CASE_TBL a, CASE2_TBL b;
 five | NULLIF(a.i,b.i) | NULLIF(b.i,4) 
------+-----------------+---------------
      |                 |             1
      |               2 |             1
      |               3 |             1
      |               4 |             1
      |               1 |             2
      |                 |             2
      |               3 |             2
      |               4 |             2
      |               1 |             3
      |               2 |             3
      |                 |             3
      |               4 |             3
      |               1 |             2
      |                 |             2
      |               3 |             2
      |               4 |             2
      |                 |             1
      |               2 |             1
      |               3 |             1
      |               4 |             1
      |               1 |              
      |               2 |              
      |               3 |              
      |               4 |              
(24 rows)

