SELECT * FROM pg_authid WHERE rolname = 'test_def_inherit';
     rolname      | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcanlogin | rolreplication | rolbypassrls | rolconnlimit | rolpassword | rolvaliduntil 
------------------+----------+------------+---------------+-------------+-------------+----------------+--------------+--------------+-------------+---------------
 test_def_inherit | f        | t          | f             | f           | f           | f              | f            |           -1 |             | 
(1 row)

