SELECT * FROM pg_authid WHERE rolname = 'test_inherit';
   rolname    | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcanlogin | rolreplication | rolbypassrls | rolconnlimit | rolpassword | rolvaliduntil 
--------------+----------+------------+---------------+-------------+-------------+----------------+--------------+--------------+-------------+---------------
 test_inherit | f        | f          | f             | f           | f           | f              | f            |           -1 |             | 
(1 row)

