SELECT * FROM pg_authid WHERE rolname = 'test_createrole';
     rolname     | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcanlogin | rolreplication | rolbypassrls | rolconnlimit | rolpassword | rolvaliduntil 
-----------------+----------+------------+---------------+-------------+-------------+----------------+--------------+--------------+-------------+---------------
 test_createrole | f        | t          | f             | f           | f           | f              | f            |           -1 |             | 
(1 row)

