SELECT * FROM pg_authid WHERE rolname = 'test_role_canlogin';
      rolname       | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcanlogin | rolreplication | rolbypassrls | rolconnlimit | rolpassword | rolvaliduntil 
--------------------+----------+------------+---------------+-------------+-------------+----------------+--------------+--------------+-------------+---------------
 test_role_canlogin | f        | t          | f             | f           | t           | f              | f            |           -1 |             | 
(1 row)

