SELECT * FROM pg_authid WHERE rolname = 'test_superuser';
    rolname     | rolsuper | rolinherit | rolcreaterole | rolcreatedb | rolcanlogin | rolreplication | rolbypassrls | rolconnlimit | rolpassword | rolvaliduntil 
----------------+----------+------------+---------------+-------------+-------------+----------------+--------------+--------------+-------------+---------------
 test_superuser | f        | t          | f             | f           | f           | f              | f            |           -1 |             | 
(1 row)

