select value, json_typeof(value)  from (values (json '123.4'),  (json '-1'),  (json '"foo"'),  (json 'true'),  (json 'false'),  (json 'null'),  (json '[1, 2, 3]'),  (json '[]'),  (json '{"x":"foo", "y":123}'),  (json '{}'),  (NULL::json))  as data(value);
        value         | json_typeof 
----------------------+-------------
 123.4                | number
 -1                   | number
 "foo"                | string
 true                 | boolean
 false                | boolean
 null                 | null
 [1, 2, 3]            | array
 []                   | array
 {"x":"foo", "y":123} | object
 {}                   | object
                      | 
(11 rows)

