explain (costs off)  select * from ec1,  (select ff + 1 as x from  (select ff + 2 as ff from ec1  union all  select ff + 3 as ff from ec1) ss0  union all  select ff + 4 as x from ec1) as ss1  where ss1.x = ec1.f1 and ec1.ff = 42::int8 and ec1.ff = ec1.f1;
                            QUERY PLAN                             
-------------------------------------------------------------------
 Nested Loop
   Join Filter: ((((ec1_1.ff + 2) + 1)) = ec1.f1)
   ->  Index Scan using ec1_pkey on ec1
         Index Cond: ((ff = '42'::bigint) AND (ff = '42'::bigint))
         Filter: (ff = f1)
   ->  Append
         ->  Index Scan using ec1_expr2 on ec1 ec1_1
               Index Cond: (((ff + 2) + 1) = '42'::bigint)
         ->  Index Scan using ec1_expr3 on ec1 ec1_2
               Index Cond: (((ff + 3) + 1) = '42'::bigint)
         ->  Index Scan using ec1_expr4 on ec1 ec1_3
               Index Cond: ((ff + 4) = '42'::bigint)
(12 rows)

