explain (costs off) insert into insertconflicttest values(0, 'Crowberry') on conflict (key, fruit) do update set fruit = excluded.fruit  where exists (select 1 from insertconflicttest ii where ii.key = excluded.key);
                                  QUERY PLAN                                   
-------------------------------------------------------------------------------
 Insert on insertconflicttest
   Conflict Resolution: UPDATE
   Conflict Arbiter Indexes: op_index_key, collation_index_key, both_index_key
   Conflict Filter: (alternatives: SubPlan 1 or hashed SubPlan 2)
   ->  Result
   SubPlan 1
     ->  Index Only Scan using both_index_expr_key on insertconflicttest ii
           Index Cond: (key = excluded.key)
   SubPlan 2
     ->  Seq Scan on insertconflicttest ii_1
(10 rows)

