UPDATE x1 SET b = b || '_updt' WHERE f_leak(b) RETURNING *;
NOTICE:  00000: f_leak => abc
NOTICE:  00000: f_leak => bcd
NOTICE:  00000: f_leak => cde
NOTICE:  00000: f_leak => def
NOTICE:  00000: f_leak => efg
NOTICE:  00000: f_leak => fgh
NOTICE:  00000: f_leak => fgh
NOTICE:  00000: f_leak => fgh
 a |    b     |         c         
---+----------+-------------------
 1 | abc_updt | rls_regress_user1
 2 | bcd_updt | rls_regress_user1
 3 | cde_updt | rls_regress_user2
 4 | def_updt | rls_regress_user2
 5 | efg_updt | rls_regress_user1
 6 | fgh_updt | rls_regress_user1
 7 | fgh_updt | rls_regress_user2
 8 | fgh_updt | rls_regress_user2
(8 rows)

UPDATE 8
