SELECT * FROM document WHERE f_leak(dtitle) ORDER BY did;
NOTICE:  00000: f_leak => my first novel
NOTICE:  00000: f_leak => my second novel
NOTICE:  00000: f_leak => my science fiction
NOTICE:  00000: f_leak => my first manga
NOTICE:  00000: f_leak => my second manga
NOTICE:  00000: f_leak => great science fiction
NOTICE:  00000: f_leak => great technology book
NOTICE:  00000: f_leak => great manga
 did | cid | dlevel |      dauthor      |        dtitle         
-----+-----+--------+-------------------+-----------------------
   1 |  11 |      1 | rls_regress_user1 | my first novel
   2 |  11 |      2 | rls_regress_user1 | my second novel
   3 |  22 |      2 | rls_regress_user1 | my science fiction
   4 |  44 |      1 | rls_regress_user1 | my first manga
   5 |  44 |      2 | rls_regress_user1 | my second manga
   6 |  22 |      1 | rls_regress_user2 | great science fiction
   7 |  33 |      2 | rls_regress_user2 | great technology book
   8 |  44 |      1 | rls_regress_user2 | great manga
(8 rows)

