SELECT * FROM document NATURAL JOIN category WHERE f_leak(dtitle) ORDER BY did;
NOTICE:  00000: f_leak => my first novel
NOTICE:  00000: f_leak => my second novel
NOTICE:  00000: f_leak => my science fiction
NOTICE:  00000: f_leak => my first manga
NOTICE:  00000: f_leak => my second manga
NOTICE:  00000: f_leak => great science fiction
NOTICE:  00000: f_leak => great technology book
NOTICE:  00000: f_leak => great manga
 cid | did | dlevel |      dauthor      |        dtitle         |      cname      
-----+-----+--------+-------------------+-----------------------+-----------------
  11 |   1 |      1 | rls_regress_user1 | my first novel        | novel
  11 |   2 |      2 | rls_regress_user1 | my second novel       | novel
  22 |   3 |      2 | rls_regress_user1 | my science fiction    | science fiction
  44 |   4 |      1 | rls_regress_user1 | my first manga        | manga
  44 |   5 |      2 | rls_regress_user1 | my second manga       | manga
  22 |   6 |      1 | rls_regress_user2 | great science fiction | science fiction
  33 |   7 |      2 | rls_regress_user2 | great technology book | technology
  44 |   8 |      1 | rls_regress_user2 | great manga           | manga
(8 rows)

