SELECT * FROM document TABLESAMPLE BERNOULLI(50) REPEATABLE(0)  WHERE f_leak(dtitle) ORDER BY did;
NOTICE:  00000: f_leak => my first manga
NOTICE:  00000: f_leak => my second manga
NOTICE:  00000: f_leak => great science fiction
NOTICE:  00000: f_leak => great manga
 did | cid | dlevel |      dauthor      |        dtitle         
-----+-----+--------+-------------------+-----------------------
   4 |  44 |      1 | rls_regress_user1 | my first manga
   5 |  44 |      2 | rls_regress_user1 | my second manga
   6 |  22 |      1 | rls_regress_user2 | great science fiction
   8 |  44 |      1 | rls_regress_user2 | great manga
(4 rows)

