SELECT '' AS to_char_20, to_char(val, E'99999 "text" 9999 "9999" 999 "\\"text between quote marks\\"" 9999') FROM num_data;
 to_char_20 |                          to_char                          
------------+-----------------------------------------------------------
            |       text      9999     "text between quote marks"     0
            |       text      9999     "text between quote marks"     0
            |       text    -3 9999 433 "text between quote marks" 8492
            |       text      9999     "text between quote marks"     4
            |       text      9999  779 "text between quote marks" 9461
            |       text      9999    1 "text between quote marks" 6397
            |       text      9999    9 "text between quote marks" 3902
            |       text    -8 9999 302 "text between quote marks" 8485
            |       text      9999    7 "text between quote marks" 4881
            |       text    -2 9999 492 "text between quote marks" 6804
(10 rows)

