create function sp_add_user(a_login text) returns int as $$  declare my_id_user int;  begin  my_id_user = sp_id_user( a_login );  IF my_id_user > 0 THEN  RETURN -1; -- error code for existing user  END IF;  INSERT INTO users ( login ) VALUES ( a_login );  my_id_user = sp_id_user( a_login );  IF my_id_user = 0 THEN  RETURN -2; -- error code for insertion failure  END IF;  RETURN my_id_user;  end$$ language plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
ERROR:  42601: syntax error at end of input
LINE 1: ...nsertion failure  END IF;  RETURN my_id_user;  end$$ languag...
                                                             ^
