create function namedparmcursor_test3() returns void as $$  declare  c1 cursor (param1 int, param2 int) for select * from rc_test where a > param1 and b > param2;  begin  open c1(param2 := 20, 21);  end  $$ language plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
ERROR:  42601: value for parameter "param2" of cursor "c1" specified more than once
LINE 1: ...am1 and b > param2;  begin  open c1(param2 := 20, 21);  end ...
                                                             ^
