create function namedparmcursor_test5() returns void as $$  declare  c1 cursor (p1 int, p2 int) for  select * from tenk1 where thousand = p1 and tenthous = p2;  begin  open c1 (p2 := 77, p2 := 42);  end  $$ language plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
ERROR:  42601: value for parameter "p2" of cursor "c1" specified more than once
LINE 1: ... p1 and tenthous = p2;  begin  open c1 (p2 := 77, p2 := 42);...
                                                             ^
