create function bad_sql2() returns int as $$  declare r record;  begin  for r in select I fought the law, the law won LOOP  raise notice 'in loop';  end loop;  return 5;  end;$$ language plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
ERROR:  42601: syntax error at or near "the"
LINE 1: ...eclare r record;  begin  for r in select I fought the law, t...
                                                             ^
