create or replace function footest() returns void as $$  declare  x record;  p1 int := 2;  p3 text := 'foo';  begin  -- too many rows  select * from foo where f1 > p1 or f1::text = p3 into strict x;  raise notice 'x.f1 = %, x.f2 = %', x.f1, x.f2;  end$$ language plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
ERROR:  42601: syntax error at end of input
LINE 1: ...aise notice 'x.f1 = %, x.f2 = %', x.f1, x.f2;  end$$ languag...
                                                             ^
