create function tg_pslot_bu() returns trigger as '  begin  if new.slotname != old.slotname then  delete from PSlot where slotname = old.slotname;  insert into PSlot (  slotname,  pfname,  slotlink,  backlink  ) values (  new.slotname,  new.pfname,  new.slotlink,  new.backlink  );  return null;  end if;  return new;  end;  ' language plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
CREATE FUNCTION
