create function tg_wslot_bu() returns trigger as '  begin  if new.slotname != old.slotname then  delete from WSlot where slotname = old.slotname;  insert into WSlot (  slotname,  roomno,  slotlink,  backlink  ) values (  new.slotname,  new.roomno,  new.slotlink,  new.backlink  );  return null;  end if;  return new;  end;  ' language plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
CREATE FUNCTION
