CREATE FUNCTION nonsimple_expr_test() RETURNS text[] AS $$  DECLARE  arr text[];  lr text;  i integer;  BEGIN  arr := array[array['foo','bar'], array['baz', 'quux']];  lr := 'fool';  i := 1;  -- use sub-SELECTs to make expressions non-simple  arr[(SELECT i)][(SELECT i+1)] := (SELECT lr);  RETURN arr;  END;  $$ LANGUAGE plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
ERROR:  42601: syntax error at end of input
LINE 1: ...(SELECT i+1)] := (SELECT lr);  RETURN arr;  END;  $$ LANGUAG...
                                                             ^
