create function tg_hslot_bu() returns trigger as '  begin  if new.slotname != old.slotname or new.hubname != old.hubname then  delete from HSlot where slotname = old.slotname;  insert into HSlot (  slotname,  hubname,  slotno,  slotlink  ) values (  new.slotname,  new.hubname,  new.slotno,  new.slotlink  );  return null;  end if;  return new;  end;  ' language plpgsql;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE FUNCTION
CREATE FUNCTION
