explain (costs off)  select a.f1, b.f1, t.thousand, t.tenthous from  tenk1 t,  (select sum(f1)+1 as f1 from int4_tbl i4a) a,  (select sum(f1) as f1 from int4_tbl i4b) b  where b.f1 = t.thousand and a.f1 = b.f1 and (a.f1+b.f1+999) = t.tenthous;
                                 QUERY PLAN                                  
-----------------------------------------------------------------------------
 Hash Join
   Hash Cond: (t.thousand = (sum(i4b.f1)))
   Join Filter: (((((sum(i4a.f1) + 1)) + (sum(i4b.f1))) + 999) = t.tenthous)
   ->  Hash Join
         Hash Cond: (t.thousand = ((sum(i4a.f1) + 1)))
         ->  Seq Scan on tenk1 t
         ->  Hash
               ->  Aggregate
                     ->  Seq Scan on int4_tbl i4a
   ->  Hash
         ->  Aggregate
               ->  Seq Scan on int4_tbl i4b
(12 rows)

