SELECT '' AS "xxx", t1.i, k, t  FROM J1_TBL t1 CROSS JOIN J2_TBL t2;
 xxx | i | k  |   t   
-----+---+----+-------
     | 1 | -1 | one
     | 2 | -1 | two
     | 3 | -1 | three
     | 4 | -1 | four
     | 5 | -1 | five
     | 6 | -1 | six
     | 7 | -1 | seven
     | 8 | -1 | eight
     | 0 | -1 | zero
     |   | -1 | null
     |   | -1 | zero
     | 1 |  2 | one
     | 2 |  2 | two
     | 3 |  2 | three
     | 4 |  2 | four
     | 5 |  2 | five
     | 6 |  2 | six
     | 7 |  2 | seven
     | 8 |  2 | eight
     | 0 |  2 | zero
     |   |  2 | null
     |   |  2 | zero
     | 1 | -3 | one
     | 2 | -3 | two
     | 3 | -3 | three
     | 4 | -3 | four
     | 5 | -3 | five
     | 6 | -3 | six
     | 7 | -3 | seven
     | 8 | -3 | eight
     | 0 | -3 | zero
     |   | -3 | null
     |   | -3 | zero
     | 1 |  4 | one
     | 2 |  4 | two
     | 3 |  4 | three
     | 4 |  4 | four
     | 5 |  4 | five
     | 6 |  4 | six
     | 7 |  4 | seven
     | 8 |  4 | eight
     | 0 |  4 | zero
     |   |  4 | null
     |   |  4 | zero
     | 1 | -5 | one
     | 2 | -5 | two
     | 3 | -5 | three
     | 4 | -5 | four
     | 5 | -5 | five
     | 6 | -5 | six
     | 7 | -5 | seven
     | 8 | -5 | eight
     | 0 | -5 | zero
     |   | -5 | null
     |   | -5 | zero
     | 1 | -5 | one
     | 2 | -5 | two
     | 3 | -5 | three
     | 4 | -5 | four
     | 5 | -5 | five
     | 6 | -5 | six
     | 7 | -5 | seven
     | 8 | -5 | eight
     | 0 | -5 | zero
     |   | -5 | null
     |   | -5 | zero
     | 1 |    | one
     | 2 |    | two
     | 3 |    | three
     | 4 |    | four
     | 5 |    | five
     | 6 |    | six
     | 7 |    | seven
     | 8 |    | eight
     | 0 |    | zero
     |   |    | null
     |   |    | zero
     | 1 |    | one
     | 2 |    | two
     | 3 |    | three
     | 4 |    | four
     | 5 |    | five
     | 6 |    | six
     | 7 |    | seven
     | 8 |    | eight
     | 0 |    | zero
     |   |    | null
     |   |    | zero
     | 1 |  0 | one
     | 2 |  0 | two
     | 3 |  0 | three
     | 4 |  0 | four
     | 5 |  0 | five
     | 6 |  0 | six
     | 7 |  0 | seven
     | 8 |  0 | eight
     | 0 |  0 | zero
     |   |  0 | null
     |   |  0 | zero
(99 rows)

