explain (costs off)  select * from int8_tbl a,  int8_tbl x left join lateral (select a.q1 from int4_tbl y) ss(z)  on x.q2 = ss.z;
                QUERY PLAN                
------------------------------------------
 Nested Loop
   ->  Seq Scan on int8_tbl a
   ->  Merge Left Join
         Merge Cond: (x.q2 = (a.q1))
         ->  Sort
               Sort Key: x.q2
               ->  Seq Scan on int8_tbl x
         ->  Sort
               Sort Key: (a.q1)
               ->  Seq Scan on int4_tbl y
(10 rows)

