explain (verbose, costs off)  select * from int4_tbl i left join  lateral (select * from int2_tbl j where i.f1 = j.f1) k on true;
                QUERY PLAN                 
-------------------------------------------
 Merge Left Join
   Output: i.f1, j.f1
   Merge Cond: (i.f1 = j.f1)
   ->  Sort
         Output: i.f1
         Sort Key: i.f1
         ->  Seq Scan on public.int4_tbl i
               Output: i.f1
   ->  Sort
         Output: j.f1
         Sort Key: j.f1
         ->  Seq Scan on public.int2_tbl j
               Output: j.f1
(13 rows)

