explain (verbose, costs off)  select * from  int8_tbl c left join (  int8_tbl a left join (select q1, coalesce(q2,42) as x from int8_tbl b) ss1  on a.q2 = ss1.q1  cross join  lateral (select q1, coalesce(ss1.x,q2) as y from int8_tbl d) ss2  ) on c.q2 = ss2.q1,  lateral (select ss2.y offset 0) ss3;
                                                                                     QUERY PLAN                                                                                     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Nested Loop
   Output: c.q1, c.q2, a.q1, a.q2, b.q1, (COALESCE(b.q2, '42'::bigint)), d.q1, (COALESCE((COALESCE(b.q2, '42'::bigint)), d.q2)), ((COALESCE((COALESCE(b.q2, '42'::bigint)), d.q2)))
   ->  Hash Right Join
         Output: c.q1, c.q2, a.q1, a.q2, b.q1, d.q1, (COALESCE(b.q2, '42'::bigint)), (COALESCE((COALESCE(b.q2, '42'::bigint)), d.q2))
         Hash Cond: (d.q1 = c.q2)
         ->  Nested Loop
               Output: a.q1, a.q2, b.q1, d.q1, (COALESCE(b.q2, '42'::bigint)), (COALESCE((COALESCE(b.q2, '42'::bigint)), d.q2))
               ->  Merge Left Join
                     Output: a.q1, a.q2, b.q1, (COALESCE(b.q2, '42'::bigint))
                     Merge Cond: (a.q2 = b.q1)
                     ->  Sort
                           Output: a.q1, a.q2
                           Sort Key: a.q2
                           ->  Seq Scan on public.int8_tbl a
                                 Output: a.q1, a.q2
                     ->  Sort
                           Output: b.q1, (COALESCE(b.q2, '42'::bigint))
                           Sort Key: b.q1
                           ->  Seq Scan on public.int8_tbl b
                                 Output: b.q1, COALESCE(b.q2, '42'::bigint)
               ->  Seq Scan on public.int8_tbl d
                     Output: d.q1, COALESCE((COALESCE(b.q2, '42'::bigint)), d.q2)
         ->  Hash
               Output: c.q1, c.q2
               ->  Seq Scan on public.int8_tbl c
                     Output: c.q1, c.q2
   ->  Result
         Output: (COALESCE((COALESCE(b.q2, '42'::bigint)), d.q2))
(28 rows)

