explain (verbose, costs off)  select * from  (select 1 as x offset 0) x cross join (select 2 as y offset 0) y  left join lateral (  select * from (select 3 as z offset 0) z where z.z = x.x  ) zz on zz.z = y.y;
                  QUERY PLAN                  
----------------------------------------------
 Nested Loop Left Join
   Output: (1), (2), (3)
   Join Filter: (((3) = (1)) AND ((3) = (2)))
   ->  Nested Loop
         Output: (1), (2)
         ->  Result
               Output: 1
         ->  Result
               Output: 2
   ->  Result
         Output: 3
(11 rows)

