explain (verbose, costs off)  select * from  (values (0,9998), (1,1000)) v(id,x),  lateral (select f1 from int4_tbl  where f1 = any (select unique1 from tenk1  where unique2 = v.x offset 0)) ss;
                                  QUERY PLAN                                  
------------------------------------------------------------------------------
 Nested Loop
   Output: "*VALUES*".column1, "*VALUES*".column2, int4_tbl.f1
   ->  Values Scan on "*VALUES*"
         Output: "*VALUES*".column1, "*VALUES*".column2
   ->  Hash Join
         Output: int4_tbl.f1
         Hash Cond: (int4_tbl.f1 = tenk1.unique1)
         ->  Seq Scan on public.int4_tbl
               Output: int4_tbl.f1
         ->  Hash
               Output: tenk1.unique1
               ->  Unique
                     Output: tenk1.unique1
                     ->  Sort
                           Output: tenk1.unique1
                           Sort Key: tenk1.unique1
                           ->  Seq Scan on public.tenk1
                                 Output: tenk1.unique1
                                 Filter: (tenk1.unique2 = "*VALUES*".column2)
(19 rows)

