explain (verbose, costs off)  update dcomptable set d1[1].r = d1[1].r - 1, d1[1].i = d1[1].i + 1  where d1[1].i > 0;
                                                   QUERY PLAN                                                   
----------------------------------------------------------------------------------------------------------------
 Update on public.dcomptable
   ->  Seq Scan on public.dcomptable
         Output: (d1[1].r := (d1[1].r - '1'::double precision))[1].i := (d1[1].i + '1'::double precision), ctid
         Filter: (dcomptable.d1[1].i > '0'::double precision)
(4 rows)

