SELECT nspname, opcname, amname, rolname  FROM pg_opclass o, pg_am m, pg_namespace n, pg_authid a  WHERE o.opcmethod = m.oid AND o.opcnamespace = n.oid AND o.opcowner = a.oid  AND n.nspname IN ('alt_nsp1', 'alt_nsp2')  ORDER BY nspname, opcname;
 nspname  | opcname  | amname |       rolname       
----------+----------+--------+---------------------
 alt_nsp2 | alt_opc2 | hash   | regtest_alter_user3
(1 row)

