DROP USER regtest_alter_user3;
ERROR:  2BP01: role "regtest_alter_user3" cannot be dropped because some objects depend on it
DETAIL:  owner of text search configuration alt_ts_conf2
owner of text search dictionary alt_ts_dict2
owner of operator class alt_opc2 for access method hash
owner of operator family alt_opf2 for access method hash
owner of operator @-@(integer,integer)
owner of conversion alt_conv2
owner of function alt_agg2(integer)
owner of function alt_func2(integer)
