INSERT INTO arrtest2 VALUES(  ARRAY[[[113,142],[1,147]]],  ARRAY[1.1,1.2,1.3]::float8[],  ARRAY[1.1,1.2,1.3],  ARRAY[[['aaa','aab'],['aba','abb'],['aca','acb']],[['baa','bab'],['bba','bbb'],['bca','bcb']]],  ARRAY['19620326','19931223','19970117']::timestamp[]  );
ERROR:  42P01: relation "arrtest2" does not exist
LINE 1: INSERT INTO arrtest2 VALUES(  ARRAY[[[113,142],[1,147]]],  A...
                    ^
