CREATE TEMP VIEW fdv3 AS  SELECT id, keywords, title, body, created  FROM articles  GROUP BY id  UNION  SELECT id, keywords, title, body, created  FROM articles  GROUP BY id;
NOTICE:  00000: test_event_trigger: ddl_command_start CREATE VIEW
ERROR:  42P01: relation "articles" does not exist
LINE 1: ...  SELECT id, keywords, title, body, created  FROM articles  ...
                                                             ^
