DO $$  DECLARE  objtype text;  BEGIN  FOR objtype IN VALUES ('toast table'), ('index column'), ('sequence column'),  ('toast table column'), ('view column'), ('materialized view column')  LOOP  BEGIN  PERFORM pg_get_object_address(objtype, '{one}', '{}');  EXCEPTION WHEN invalid_parameter_value THEN  RAISE WARNING 'error for %: %', objtype, sqlerrm;  END;  END LOOP;  END;  $$;
WARNING:  01000: error for toast table: unsupported object type "toast table"
WARNING:  01000: error for index column: unsupported object type "index column"
WARNING:  01000: error for sequence column: unsupported object type "sequence column"
WARNING:  01000: error for toast table column: unsupported object type "toast table column"
WARNING:  01000: error for view column: unsupported object type "view column"
WARNING:  01000: error for materialized view column: unsupported object type "materialized view column"
DO
