ALTER TABLE main_table DROP COLUMN b;
NOTICE:  00000: test_event_trigger: ddl_command_start ALTER TABLE
ERROR:  2BP01: cannot drop table main_table column b because other objects depend on it
DETAIL:  trigger after_upd_b_row_trig on table main_table depends on table main_table column b
trigger after_upd_a_b_row_trig on table main_table depends on table main_table column b
trigger after_upd_b_stmt_trig on table main_table depends on table main_table column b
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
