insert into upsert values(3, 'orange') on conflict (key) do update set color = 'updated ' || upsert.color;
WARNING:  01000: before insert (new): (3,orange)
WARNING:  01000: before update (old): (3,"red trig modified")
WARNING:  01000: before update (new): (3,"updated red trig modified")
WARNING:  01000: after update (old): (3,"red trig modified")
WARNING:  01000: after update (new): (3,"updated red trig modified")
INSERT 0 1
