DROP SCHEMA schema_one, schema_two CASCADE;
NOTICE:  00000: test_event_trigger: ddl_command_start DROP SCHEMA
NOTICE:  00000: drop cascades to 7 other objects
DETAIL:  drop cascades to table schema_two.table_two
drop cascades to table schema_two.table_three
drop cascades to function schema_two.add(integer,integer)
drop cascades to function schema_two.newton(integer)
drop cascades to table schema_one.table_one
drop cascades to table schema_one."table two"
drop cascades to table schema_one.table_three
NOTICE:  00000: test_event_trigger: ddl_command_start DROP TABLE
CONTEXT:  SQL statement "DROP TABLE IF EXISTS audit_tbls.schema_two_table_two"
PL/pgSQL function test_evtrig_dropped_objects() line 1 at EXECUTE
NOTICE:  00000: table "schema_two_table_two" does not exist, skipping
CONTEXT:  SQL statement "DROP TABLE IF EXISTS audit_tbls.schema_two_table_two"
PL/pgSQL function test_evtrig_dropped_objects() line 1 at EXECUTE
NOTICE:  00000: test_event_trigger: ddl_command_start DROP TABLE
CONTEXT:  SQL statement "DROP TABLE IF EXISTS audit_tbls.schema_two_table_three"
PL/pgSQL function test_evtrig_dropped_objects() line 1 at EXECUTE
NOTICE:  00000: test_event_trigger: ddl_command_start DROP TABLE
CONTEXT:  SQL statement "DROP TABLE IF EXISTS audit_tbls.audit_tbls_schema_two_table_three"
PL/pgSQL function test_evtrig_dropped_objects() line 1 at EXECUTE
SQL statement "DROP TABLE IF EXISTS audit_tbls.schema_two_table_three"
PL/pgSQL function test_evtrig_dropped_objects() line 1 at EXECUTE
NOTICE:  00000: table "audit_tbls_schema_two_table_three" does not exist, skipping
CONTEXT:  SQL statement "DROP TABLE IF EXISTS audit_tbls.audit_tbls_schema_two_table_three"
PL/pgSQL function test_evtrig_dropped_objects() line 1 at EXECUTE
SQL statement "DROP TABLE IF EXISTS audit_tbls.schema_two_table_three"
PL/pgSQL function test_evtrig_dropped_objects() line 1 at EXECUTE
ERROR:  P0001: object audit_tbls.schema_two_table_three of type table cannot be dropped
CONTEXT:  SQL statement "DROP TABLE IF EXISTS audit_tbls.schema_two_table_three"
PL/pgSQL function test_evtrig_dropped_objects() line 1 at EXECUTE
