SELECT definition FROM pg_rules WHERE tablename = 'hats' ORDER BY rulename;
                                  definition                                  
------------------------------------------------------------------------------
 CREATE RULE hat_nosert_all AS                                               +
     ON INSERT TO hats DO INSTEAD  INSERT INTO hat_data (hat_name, hat_color)+
   VALUES (new.hat_name, new.hat_color) ON CONFLICT DO NOTHING               +
   RETURNING hat_data.hat_name,                                              +
     hat_data.hat_color;
(1 row)

