EXPLAIN (costs off) WITH data(hat_name, hat_color) AS (  VALUES ('h8', 'green'),  ('h9', 'blue'),  ('h7', 'forbidden')  )  INSERT INTO hats  SELECT * FROM data  RETURNING *;
                                           QUERY PLAN                                            
-------------------------------------------------------------------------------------------------
 Insert on hat_data
   Conflict Resolution: UPDATE
   Conflict Arbiter Indexes: hat_data_unique_idx
   Conflict Filter: ((excluded.hat_color <> 'forbidden'::bpchar) AND (hat_data.* <> excluded.*))
   CTE data
     ->  Values Scan on "*VALUES*"
   ->  CTE Scan on data
(7 rows)

