SELECT foo, length(foo) FROM regexp_split_to_table('the quick brown fox jumps over the lazy dog', '') AS foo;
 foo | length 
-----+--------
 t   |      1
 h   |      1
 e   |      1
     |      1
 q   |      1
 u   |      1
 i   |      1
 c   |      1
 k   |      1
     |      1
 b   |      1
 r   |      1
 o   |      1
 w   |      1
 n   |      1
     |      1
 f   |      1
 o   |      1
 x   |      1
     |      1
 j   |      1
 u   |      1
 m   |      1
 p   |      1
 s   |      1
     |      1
 o   |      1
 v   |      1
 e   |      1
 r   |      1
     |      1
 t   |      1
 h   |      1
 e   |      1
     |      1
 l   |      1
 a   |      1
 z   |      1
 y   |      1
     |      1
 d   |      1
 o   |      1
 g   |      1
(43 rows)

