explain (costs off) select * from nv_parent where d between '2011-08-01' and '2011-08-31';
                                QUERY PLAN                                 
---------------------------------------------------------------------------
 Append
   ->  Seq Scan on nv_parent
         Filter: ((d >= '2011-08-01'::date) AND (d <= '2011-08-31'::date))
   ->  Seq Scan on nv_child_2010
         Filter: ((d >= '2011-08-01'::date) AND (d <= '2011-08-31'::date))
   ->  Seq Scan on nv_child_2011
         Filter: ((d >= '2011-08-01'::date) AND (d <= '2011-08-31'::date))
(7 rows)

