select relname, conname, coninhcount, conislocal, connoinherit  from pg_constraint c, pg_class r  where relname like 'test_inh_check%' and c.conrelid = r.oid  order by 1, 2;
       relname        |        conname         | coninhcount | conislocal | connoinherit 
----------------------+------------------------+-------------+------------+--------------
 test_inh_check       | bmerged                |           0 | t          | f
 test_inh_check       | bnoinherit             |           0 | t          | t
 test_inh_check       | test_inh_check_a_check |           0 | t          | f
 test_inh_check_child | blocal                 |           0 | t          | f
 test_inh_check_child | bmerged                |           1 | t          | f
 test_inh_check_child | test_inh_check_a_check |           1 | f          | f
(6 rows)

